version: "3.8"
services: 
  
  cobiro-scrapper:
    build: 
      dockerfile: Dockerfile
      context: ./
    command: yarn dev
    ports: 
      - 4000:4000
    volumes: 
      - type: volume
        target: /home/eko9x9/app/temp

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports: 
      - "5432:5432"
    environment:
      TZ: "Asia/Jakarta"
      PGTZ: "Asia/Jakarta"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cobiro_scrapp
    volumes: 
      - type: volume
        source: local
        target: /var/lib/postgresql/data
    networks: 
      - default

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "5555:80"
    networks: 
      - default
    environment:
      PGADMIN_DEFAULT_EMAIL: test@test.test
      PGADMIN_DEFAULT_PASSWORD: test

volumes: 
  local:
    driver: local

networks: 
  default:
    driver: bridge